// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// destinieSimTRI2
void destinieSimTRI2(Environment envSim);
RcppExport SEXP _destinie_destinieSimTRI2(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieSimTRI2(envSim);
    return R_NilValue;
END_RCPP
}
// destinieDemographie
void destinieDemographie(Environment env);
RcppExport SEXP _destinie_destinieDemographie(SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    destinieDemographie(env);
    return R_NilValue;
END_RCPP
}
// destinieCalageSalaires
void destinieCalageSalaires(Environment envSim);
RcppExport SEXP _destinie_destinieCalageSalaires(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieCalageSalaires(envSim);
    return R_NilValue;
END_RCPP
}
// destinieSim
void destinieSim(Environment envSim);
RcppExport SEXP _destinie_destinieSim(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieSim(envSim);
    return R_NilValue;
END_RCPP
}
// destinieIndiv
void destinieIndiv(Environment envSim, int Id);
RcppExport SEXP _destinie_destinieIndiv(SEXP envSimSEXP, SEXP IdSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    Rcpp::traits::input_parameter< int >::type Id(IdSEXP);
    destinieIndiv(envSim, Id);
    return R_NilValue;
END_RCPP
}
// destinieSimIndiv
void destinieSimIndiv(Environment envSim);
RcppExport SEXP _destinie_destinieSimIndiv(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieSimIndiv(envSim);
    return R_NilValue;
END_RCPP
}
// destinieSimAgefin
void destinieSimAgefin(Environment envSim);
RcppExport SEXP _destinie_destinieSimAgefin(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieSimAgefin(envSim);
    return R_NilValue;
END_RCPP
}
// destinieFinCar
void destinieFinCar(Environment envSim);
RcppExport SEXP _destinie_destinieFinCar(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieFinCar(envSim);
    return R_NilValue;
END_RCPP
}
// destinieSimOptim
void destinieSimOptim(Environment envSim);
RcppExport SEXP _destinie_destinieSimOptim(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieSimOptim(envSim);
    return R_NilValue;
END_RCPP
}
// destinieImputSal
void destinieImputSal(Environment envSim);
RcppExport SEXP _destinie_destinieImputSal(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieImputSal(envSim);
    return R_NilValue;
END_RCPP
}
// destinieTransMdt
void destinieTransMdt(Environment envSim);
RcppExport SEXP _destinie_destinieTransMdt(SEXP envSimSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Environment >::type envSim(envSimSEXP);
    destinieTransMdt(envSim);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_destinie_destinieSimTRI2", (DL_FUNC) &_destinie_destinieSimTRI2, 1},
    {"_destinie_destinieDemographie", (DL_FUNC) &_destinie_destinieDemographie, 1},
    {"_destinie_destinieCalageSalaires", (DL_FUNC) &_destinie_destinieCalageSalaires, 1},
    {"_destinie_destinieSim", (DL_FUNC) &_destinie_destinieSim, 1},
    {"_destinie_destinieIndiv", (DL_FUNC) &_destinie_destinieIndiv, 2},
    {"_destinie_destinieSimIndiv", (DL_FUNC) &_destinie_destinieSimIndiv, 1},
    {"_destinie_destinieSimAgefin", (DL_FUNC) &_destinie_destinieSimAgefin, 1},
    {"_destinie_destinieFinCar", (DL_FUNC) &_destinie_destinieFinCar, 1},
    {"_destinie_destinieSimOptim", (DL_FUNC) &_destinie_destinieSimOptim, 1},
    {"_destinie_destinieImputSal", (DL_FUNC) &_destinie_destinieImputSal, 1},
    {"_destinie_destinieTransMdt", (DL_FUNC) &_destinie_destinieTransMdt, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_destinie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
