# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

destinieSimTRI2 <- function(envSim) {
    invisible(.Call('_destinie_destinieSimTRI2', PACKAGE = 'destinie', envSim))
}

#' Fonction destinieDemographie
#' @description Simule en projection les évènements démographiques des individus:
#' décès, immigration, mise en couple, naissances 
#' @return Retourne le meme environnement,
#' mais projeté jusqu'à la fin de la simulation
#' @param envSim Environment 
#' @export
destinieDemographie <- function(env) {
    invisible(.Call('_destinie_destinieDemographie', PACKAGE = 'destinie', env))
}

#' Fonction destinieCalageSalaires
#' @description Cale les salaires imputés pour respecter
#' la trajectoire du Salaire Moyen Par Tête (SMPT)
#' @return Retourne le meme environnement avec des salaires modifiés
#' @param envSim Environment 
#' @export
destinieCalageSalaires <- function(envSim) {
    invisible(.Call('_destinie_destinieCalageSalaires', PACKAGE = 'destinie', envSim))
}

#' Fonction destinieSim
#' @description Calcule les droits retraites des individus.
#' Lance une simulation en utilisant la fonction SimDir. 
#' La fonction boucle sur chaque année de simulation. 
#' Pour chaque année elle boucle sur chaque individu pour 
#' le calcul des droits directs, puis boucle à nouveau sur
#'  chaque individu pour le calcul des droits indirects et 
#'  enfin boucle sur chaque individu pour le calculdu minimum
#'   vieillesse. L'avantage de la fonction destinieSim sur la 
#'   fonction destinieSimIndiv est qu'elle calcul les droits 
#'   indirects et le minimum vieillesse.
#' @return Retourne le meme environnement,
#' mais avec les droits retraites
#' @param envSim Environment 
#' @export
destinieSim <- function(envSim) {
    invisible(.Call('_destinie_destinieSim', PACKAGE = 'destinie', envSim))
}

destinieIndiv <- function(envSim, Id) {
    invisible(.Call('_destinie_destinieIndiv', PACKAGE = 'destinie', envSim, Id))
}

#' Fonction destinieSimIndiv
#' @description Calcule les droits retraites de droit direct
#' (pas le minimum vieillesse ou les réversions) 
#' @return Retourne le meme environnement,
#' mais avec les droits directs uniquement.
#' @param envSim Environment 
#' @export
destinieSimIndiv <- function(envSim) {
    invisible(.Call('_destinie_destinieSimIndiv', PACKAGE = 'destinie', envSim))
}

destinieSimAgefin <- function(envSim) {
    invisible(.Call('_destinie_destinieSimAgefin', PACKAGE = 'destinie', envSim))
}

destinieFinCar <- function(envSim) {
    invisible(.Call('_destinie_destinieFinCar', PACKAGE = 'destinie', envSim))
}

destinieSimOptim <- function(envSim) {
    invisible(.Call('_destinie_destinieSimOptim', PACKAGE = 'destinie', envSim))
}

#' Fonction destinieImputSal
#' @description Attribue des revenus d'activités aux individus. Les statuts d'activité sont déjà connus.
#' @return Retourne le même environnement,
#' mais avec des revenus d'activité.
#' @param envSim Environment 
#' @export
destinieImputSal <- function(envSim) {
    invisible(.Call('_destinie_destinieImputSal', PACKAGE = 'destinie', envSim))
}

#' Fonction destinieTransMdt
#' @description Simule les transitions sur le marché du travail
#' entre statuts d'activité
#' @return Retourne le meme environnement,
#' mais avec des status d'activité du début de la vie active
#' jusqu'au décès.
#' @param envSim Environment 
#' @export
destinieTransMdt <- function(envSim) {
    invisible(.Call('_destinie_destinieTransMdt', PACKAGE = 'destinie', envSim))
}

